services:
  bot:
    build: .
    env_file: .env
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - ./logs:/app/logs
      - ./backups:/app/backups
    extra_hosts:
      - 'host.docker.internal:host-gateway'
